version: '3'

services:
    nginx:
        image: nginx:latest
        container_name: servidor_nginx
        ports:
            - "8080:80"
        networks:
            - rede
        command: ["bash", "-c", "echo '<h1>Sistema web</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'; sleep infinity"]
    
    debian:
        image: debian:latest
        container_name: cliente_debian
        networks:
            - rede
        command: ["bash", "-c", "apt update; apt install -y curl; sleep infinity;"]
networks:
    rede:
        driver: bridge

# 1. Executar ambiente: docker-compose up -d
# 2. Acessar container cliente: docker exec -it cliente_debian bash
# 3. Via container cliente, acessar container servidor: curl http://servidor_nginx


# Ferramentas utilizadas: docker, debian, nginx, curl
